name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: xaksis/setup-gcc@v1
      with:
        gcc-version: 'latest'

    - name: Build
      run: |
        gcc -o filesystem filesystem.c