name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build
      run: |
        gcc -o filesystem filesystem.c

    - name: Static analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --error-exitcode=1 --inconclusive --force 
        --include=./headers.h
        --exclude=tests/unity.c \
        --exclude=tests/unity.h \
        --exclude=tests/unity_internals.h \
