name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC and cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck
        cppcheck --version

    - name: Build
      run: |
        gcc -o filesystem filesystem.c

    - name: Static analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck ./headers.h ./filesystem.c --enable=all --error-exitcode=1 --inconclusive --force \ 
