name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: |
        sudo apt-get update

    - name: Install cppcheck from source
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake g++ make
        git clone https://github.com/danmar/cppcheck.git
        cd cppcheck
        git checkout master
        mkdir build && cd build
        cmake ..
        make install

    - name: Build
      run: |
        gcc -o filesystem filesystem.c

    - name: Static analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --error-exitcode=1 --inconclusive --force \
        --include=./headers.h \
        --ignore-list=.cppcheck-ignore \
        .
